apiVersion: apps/v1
kind: Deployment
metadata:
  name: spm-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spm-frontend
  template:
    metadata:
      labels:
        app: spm-frontend
    spec:
      containers:
      - name: frontend
        image: laupse/spm-frontend
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: spm-frontend
spec:
  selector:
    app: spm-frontend
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30000

