apiVersion: apps/v1
kind: Deployment
metadata:
  name: spm-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spm-backend
  template:
    metadata:
      labels:
        app: spm-backend
    spec:
      containers:
      - name: backend
        image: laupse/spm-backend
        env:
        - name: PouletMayo_Db__Host
          value: mysql.default.svc.cluster.local
        - name: PouletMayo_Db__User
          value: root
        - name: PouletMayo_Db__Password
          value: password
        - name: PouletMayo_Db__Database
          value: pouletmayo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: spm-backend
spec:
  type: NodePort
  selector:
    app: spm-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001

